# install_config/install_workers/install_utils.py
"""File-copy and batch-script generation helpers used by the installer steps."""

import logging
import shutil
import sys
from pathlib import Path
from typing import Union

logger = logging.getLogger(__name__)

# Everything the runner needs at the destination, relative to the BDR source root.
REQUIRED_DIRS = ["workers"]
REQUIRED_FILES = ["deploy_fusion_runner.py", "requirements.txt"]


def get_bdr_source_dir() -> Path:
    """
    Where the Build_Deploy_Run source files (workers/, deploy_fusion_runner.py, requirements.txt) live.

    - Frozen (PyInstaller): the bundle's temp folder (sys._MEIPASS); the .spec bundles these files.
    - From source: the repository root (three levels above this file).
    """
    if getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS"):
        return Path(sys._MEIPASS)
    return Path(__file__).resolve().parents[2]


def copy_bdr_scripts(src_bdr_root: Union[str, Path], target_bdr_dir: Union[str, Path], confirm_overwrite: bool = True):
    """
    Copies workers/, deploy_fusion_runner.py and requirements.txt from the BDR source root
    into <user_project>/Build_Deploy_Run/.
    """
    src = Path(src_bdr_root)
    dst = Path(target_bdr_dir)
    logger.debug(f"copy_bdr_scripts(): '{src}' -> '{dst}' (overwrite={confirm_overwrite})")

    missing = [d for d in REQUIRED_DIRS if not (src / d).is_dir()] + \
              [f for f in REQUIRED_FILES if not (src / f).is_file()]
    if missing:
        raise FileNotFoundError(f"[BDR] Source folder {src} is missing required items: {', '.join(missing)}")

    if dst.exists() and not confirm_overwrite:
        logger.info(f"[BDR] Target exists and overwrite is disabled: {dst}. Skipping copy.")
        return

    dst.mkdir(parents=True, exist_ok=True)

    for dirname in REQUIRED_DIRS:
        src_dir, dst_dir = src / dirname, dst / dirname
        if dst_dir.exists():
            shutil.rmtree(dst_dir)
        shutil.copytree(src_dir, dst_dir, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        logger.info(f"[BDR] Directory copied: {src_dir} -> {dst_dir}")

    for filename in REQUIRED_FILES:
        shutil.copy2(src / filename, dst / filename)
        logger.info(f"[BDR] File copied: {src / filename} -> {dst / filename}")

    logger.info(f"[BDR] All required content copied to: {dst}")


# --- Batch Script Generation ---
BATCH_SCRIPT_NAME = "build_and_deploy_venv_locked.bat"

BATCH_CONTENT = r"""@echo off
REM === Build & Deploy VENV Locked Script (generated by the Build_Deploy_Run installer) ===
REM Usage:  build_and_deploy_venv_locked.bat [entrypoint] [--skip-docker | --docker] [--skip-exe | --exe] [--no-pause]
REM Defaults come from .deploy_config next to this script; arguments override them.
SETLOCAL ENABLEDELAYEDEXPANSION ENABLEEXTENSIONS
TITLE Build and Deploy - Locked Venv

REM --- Paths ---
SET "SCRIPT_DIR=%~dp0"
IF "%SCRIPT_DIR:~-1%"=="\" SET "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"
SET "VENV_DIR=%SCRIPT_DIR%\.venv"
SET "PYTHON_EXE=%VENV_DIR%\Scripts\python.exe"
FOR %%I IN ("%SCRIPT_DIR%\..") DO SET "PROJECT_DIR=%%~fI"
SET "CONFIG_FILE=%SCRIPT_DIR%\.deploy_config"
SET "TARGET_SCRIPT=%SCRIPT_DIR%\deploy_fusion_runner.py"

REM --- Banner ---
echo -------------------------------------------------
echo  BUILD AND DEPLOY SCRIPT STARTED
echo  Project:  %PROJECT_DIR%
echo  Venv:     %VENV_DIR%
echo -------------------------------------------------
echo.

IF NOT EXIST "%PYTHON_EXE%" (
    echo [ERROR] Python executable not found in venv: "%PYTHON_EXE%". Re-run the installer.
    goto :eof_error
)
IF NOT EXIST "%TARGET_SCRIPT%" (
    echo [ERROR] Deployment script not found: "%TARGET_SCRIPT%". Re-run the installer.
    goto :eof_error
)

REM --- Defaults from .deploy_config ---
SET "ENTRYPOINT="
SET "SKIP_DOCKER="
SET "SKIP_EXE="
SET "DOCKER_PATH="
IF EXIST "%CONFIG_FILE%" (
    echo [INFO] Loading defaults from "%CONFIG_FILE%"
    FOR /F "usebackq tokens=1,* delims==" %%A IN ("%CONFIG_FILE%") DO (
        IF /I "%%A"=="entrypoint" SET "ENTRYPOINT=%%B"
        IF /I "%%A"=="skip_docker" SET "SKIP_DOCKER=%%B"
        IF /I "%%A"=="skip_exe" SET "SKIP_EXE=%%B"
        IF /I "%%A"=="docker_path" SET "DOCKER_PATH=%%B"
    )
) ELSE (
    echo [INFO] No .deploy_config found; expecting the entrypoint as the first argument.
)

REM --- Command-line overrides ---
SET "FIRST_ARG=%~1"
IF DEFINED FIRST_ARG IF NOT "!FIRST_ARG:~0,2!"=="--" SET "ENTRYPOINT=!FIRST_ARG!"
:parse_args
IF "%~1"=="" GOTO :args_done
IF /I "%~1"=="--skip-docker" SET "SKIP_DOCKER=true"
IF /I "%~1"=="--docker" SET "SKIP_DOCKER=false"
IF /I "%~1"=="--skip-exe" SET "SKIP_EXE=true"
IF /I "%~1"=="--exe" SET "SKIP_EXE=false"
IF /I "%~1"=="--no-pause" SET "BDR_NO_PAUSE=1"
SHIFT
GOTO :parse_args
:args_done

IF NOT DEFINED ENTRYPOINT (
    echo [ERROR] No entrypoint. Pass it as the first argument, e.g.  %~nx0 main.py
    goto :eof_error
)

REM --- Make sure the project has a requirements.txt (from the PROJECT venv, never this tool's venv) ---
SET "PROJECT_PY=%PROJECT_DIR%\.venv\Scripts\python.exe"
IF EXIST "%PROJECT_DIR%\requirements.txt" (
    echo [INFO] Using existing project requirements.txt
) ELSE IF EXIST "%PROJECT_PY%" (
    echo [INFO] Generating requirements.txt from the project venv
    "%PROJECT_PY%" -m pip freeze --exclude-editable > "%PROJECT_DIR%\requirements.txt"
) ELSE (
    echo [INFO] No project venv found; skipping requirements.txt generation.
)

REM --- Run Deployment ---
SET RUNNER_ARGS=--entrypoint "!ENTRYPOINT!"
IF /I "!SKIP_DOCKER!"=="true" SET RUNNER_ARGS=!RUNNER_ARGS! --skip-docker
IF /I "!SKIP_EXE!"=="true" SET RUNNER_ARGS=!RUNNER_ARGS! --skip-exe
IF DEFINED DOCKER_PATH SET RUNNER_ARGS=!RUNNER_ARGS! --docker-path "!DOCKER_PATH!"
echo [INFO] Launching: "%PYTHON_EXE%" "%TARGET_SCRIPT%" !RUNNER_ARGS!
"%PYTHON_EXE%" "%TARGET_SCRIPT%" !RUNNER_ARGS!
SET "DEPLOY_EXIT_CODE=!ERRORLEVEL!"
IF NOT "!DEPLOY_EXIT_CODE!"=="0" (
    echo [ERROR] Deployment failed with exit code !DEPLOY_EXIT_CODE!. See output above and Build_Deploy_Run\logs\bdr_runner.log.
    goto :eof_error
)

echo.
echo [SUCCESS] Build and deploy process complete. Output is in "%PROJECT_DIR%\dist".
IF NOT "%BDR_NO_PAUSE%"=="1" pause
ENDLOCAL
exit /b 0

:eof_error
echo.
echo [SCRIPT FAILED]
IF NOT "%BDR_NO_PAUSE%"=="1" pause
ENDLOCAL
exit /b 1
"""


def generate_batch_script(target_dir: Union[str, Path]):
    """Writes build_and_deploy_venv_locked.bat into target_dir (the Build_Deploy_Run folder)."""
    target_dir = Path(target_dir)
    batch_path = target_dir / BATCH_SCRIPT_NAME
    try:
        target_dir.mkdir(parents=True, exist_ok=True)
        with open(batch_path, "w", encoding="utf-8", newline="\r\n") as f:
            f.write(BATCH_CONTENT)
        logger.info(f"[GEN] Batch script generated at: {batch_path}")
    except Exception as e:
        logger.error(f"[GEN] Failed to generate batch script: {e}", exc_info=True)
        raise RuntimeError(f"Failed to generate batch script: {e}") from e
